name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copiar os arquivos do repositorio
        uses: actions/checkout@v4.1.7

      - name: Roda outro comando!
        run: echo $(ls)