name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copiar os arquivos do repositorio
        uses: actions/checkout@v4.1.7

      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1' 

      - name: Instalar pacote do projeto
        run: pip install -r requirements.txt

      - name: Testar projeto
        run: pytest